### ISSUE TITLE
新版APP手机端卡死怎么解决。

### ISSUE THREAD

**Issue by ningqivip** [getlantern/forum#5023]
有谁知道4.0以下的版本不卡，但是没法上

**Comment by linstories** [comment]
手机端卡死，就版本也不能用

**Comment by wizardmly** [comment]
给你们贴下ANR日志吧
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 obj=0x750776b8 self=0xaa785400
  | sysTid=11681 nice=-10 cgrp=default sched=0/0 handle=0xad453534
  | state=S schedstat=( 690691710 130880359 951 ) utm=55 stm=13 core=0 HZ=100
  | stack=0xbe063000-0xbe065000 stackSize=8MB
  | held mutexes=
  native: #00 pc 0016c7f8  /data/app/org.getlantern.lantern-2/lib/arm/libgojni.so (???)
  native: #01 pc 0013b490  /data/app/org.getlantern.lantern-2/lib/arm/libgojni.so (???)
  at android.Android.checkForUpdates(Native method)
  at org.lantern.app.activity.LanternMainActivity.checkUpdateAvailable(LanternMainActivity.java:754)
  at org.lantern.app.activity.LanternMainActivity.access$200(LanternMainActivity.java:89)
  at org.lantern.app.activity.LanternMainActivity$16.run(LanternMainActivity.java:719)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke!(Native method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
