### ISSUE TITLE
android app crash

### ISSUE THREAD

**Issue by babytree** [getlantern/forum#9986]
FATAL EXCEPTION: main
                                                   Process: org.getlantern.lantern, PID: 25293
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{org.getlantern.lantern/org.lantern.app.activity.UpdateActivity_}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2836)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6665)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
                                                    Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
                                                       at android.app.Activity.onCreate(Activity.java:1007)
                                                       at org.lantern.app.activity.UpdateActivity_.onCreate(UpdateActivity_.java:36)
                                                       at android.app.Activity.performCreate(Activity.java:7057)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2789)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911) 
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                       at android.os.Looper.loop(Looper.java:164) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6665) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by babytree** [comment]
手机型号：小米mix2
